### ISSUE TITLE
Is there any way to get a list of params used in the given string?

### ISSUE THREAD

**Issue by mananjadhav** [36monkeys/php-stringformatter#1]
I am working on a custom formatted data with a few params (mandatory and optional).

These parameters (params)  are filled in by running database queries. So I was wondering based on the existence of params in the string template, is there a way to find the list of params that I can use to optimize the number of queries required.

```
A few sample templates would be:
-  "Receipt # {user_initials} / {account_year} / {sr_no}" 
-  "# {sr_no} / {invoice_no} - {account_year}" 
-  "# {account_year} / {sr_no} / {curr_date}" 
```

These params are configurable (restricted to a pre-defined set though) by the users and then defined for each entity as above.

--------------------
An unrelated second question, what's the best way to convert `iformat `output to a string. I am using `__toString()` for now which works fine but thought to clarify if this is the recommended way.

**Comment by msztolcman** [comment]
Ad 1. Unfortunately no, there is no way to retrieve initial format and params from `Transformer`. Current `Transformer` works on plain string, not `Formatter` instance.
Ad 2. Current official version requires explicit casting to string: `(string) iformat(...)`.

I am planning sligtly smarter version of `Transformer` where I should be able to achieve a way to retrieve format and params, and in this version also will exist explicit method to 'unfold' `Transformer` to string, but I don't know when it be ready yet.

**Comment by mananjadhav** [comment]
Okay.  Thanks. I'll might then use regex to find the list of params.

**Comment by msztolcman** [comment]
Or maybe do not use shortcuts, just use `Compiler` with your own helper? In fact, `iformat` is just simple wrapper for `Compiler::run`.  When you have `Compiler` instance, you have also access to `format` string and it's params (there is no getter, but you can use `Reflection` to get access to it. Something like:

    $compiler = new Compiler('Hello, {}', ['world'], Compiler::MODE_INDEX, 5);
    $result = $compiler->run();
    $reflection = new \ReflectionObject($compiler);
    $originalFormat = $reflection->getProperty('format');
    $originalFormat->setAccessible(true);
    $originalParams = $reflection->getProperty('params');
    $originalParams->setAccessible(true);

Not very convenient, but much better then regexps, and still you have a power of `Compiler` :)

**Comment by mananjadhav** [comment]
I was just digging through the Transformer/Compiler code. 

This looks much better than regex. Thanks (Y)

**Comment by msztolcman** [comment]
Hi again @mananjadhav :)

Your issue motivated me to be hurry with changes I planned some time :) Today morning I pushed quite-final version with changed `Transformer` engine. New version is lazy evaluated, and allows you for taking format and parameters in easy way (ie. `iformat('...', [])->getInput()->getParams()`). However, it's not stable yet, because of no real usage yet.
